Yazlab_2.1/app/views/home.py
from operator import length_hint
from flask import render_template,Blueprint, request,abort
from datetime import datetime
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from app.models.models import Arac_sorgu,GirisTarih
import pandas as pd
from app.controllers import GetCurrentUsername
import sys
sys.path.append("../")


global cred 
global app
global request1
data_10 = []
data_25 = []
data_34 = []
data_37 = []

def build():
    
    if not firebase_admin._apps:
        cred = credentials.Certificate("app./key.json") 
        app = firebase_admin.initialize_app(cred)

    
    request1 = firestore.client()
    data_25_docu = request1.collection(u'ALLCARS').document(str(25))
    data_25_doc = data_25_docu.get()._data
    data_10_docu = request1.collection(u'ALLCARS').document(str(10))
    data_10_doc = data_10_docu.get()._data
    data_34_docu = request1.collection(u'ALLCARS').document(str(34))
    data_34_doc = data_34_docu.get()._data
    data_37_docu = request1.collection(u'ALLCARS').document(str(37))
    data_37_doc = data_37_docu.get()._data

    
    x_list10=[]
    y_list10=[]
    date_list10=[]
    time_point10=[]
    doc = data_10_doc

    for value, date in doc.items():
        x_list10.append(doc[value]['x'])
        y_list10.append(doc[value]['y'])
        date_list10.append(value)
        time = value.split(" ")
        saat = time[1]
        saat_birim = saat.split(":")
        toplam = (int(saat_birim[0])*60)+(int(saat_birim[1]))
        time_point10.append(toplam)
    
    for i in range(len(x_list10)):
        veri = {
        "x": 0,
        "y": 0,
        "date": 0,
        "time_p":0
        }
        veri.update({"x": x_list10[i]})
        veri.update({"y": y_list10[i]})
        veri.update({"date": date_list10[i]})
        veri.update({"time_p": time_point10[i]})
        data_10.append(veri)

    x_list25=[]
    y_list25=[]
    date_list25=[]
    time_point25=[]
    doc = data_25_doc

    for value, date in doc.items():
        x_list25.append(doc[value]['x'])
        y_list25.append(doc[value]['y'])
        date_list25.append(value)
        time = value.split(" ")
        saat = time[1]
        saat_birim = saat.split(":")
        toplam = (int(saat_birim[0])*60)+(int(saat_birim[1]))
        time_point25.append(toplam)
    
    for i in range(len(x_list25)):
        veri = {
        "x": 0,
        "y": 0,
        "date": 0,
        "time_p":0
        }
        veri.update({"x": x_list25[i]})
        veri.update({"y": y_list25[i]})
        veri.update({"date": date_list25[i]})
        veri.update({"time_p": time_point25[i]})
        data_25.append(veri)


    x_list34=[]
    y_list34=[]
    date_list34=[]
    time_point34=[]
    doc = data_34_doc

    for value, date in doc.items():
        x_list34.append(doc[value]['x'])
        y_list34.append(doc[value]['y'])
        date_list34.append(value)
        time = value.split(" ")
        saat = time[1]
        saat_birim = saat.split(":")
        toplam = (int(saat_birim[0])*60)+(int(saat_birim[1]))
        time_point34.append(toplam)
    
    for i in range(len(x_list34)):
        veri = {
        "x": 0,
        "y": 0,
        "date": 0,
        "time_p":0
        }
        veri.update({"x": x_list34[i]})
        veri.update({"y": y_list34[i]})
        veri.update({"date": date_list34[i]})
        veri.update({"time_p": time_point34[i]})
        data_34.append(veri)

    #data_37 = get_data(data_37_doc)

    
    x_list37=[]
    y_list37=[]
    date_list37=[]
    time_point37=[]
    doc = data_37_doc

    for value, date in doc.items():
        x_list37.append(doc[value]['x'])
        y_list37.append(doc[value]['y'])
        date_list37.append(value)
        time = value.split(" ")
        saat = time[1]
        saat_birim = saat.split(":")
        toplam = (int(saat_birim[0])*60)+(int(saat_birim[1]))
        time_point37.append(toplam)
    
    for i in range(len(x_list37)):
        veri = {
        "x": 0,
        "y": 0,
        "date": 0,
        "time_p":0
        }
        veri.update({"x": x_list37[i]})
        veri.update({"y": y_list37[i]})
        veri.update({"date": date_list37[i]})
        veri.update({"time_p": time_point37[i]})
        data_37.append(veri)






def arac_bul(arac_ismi):
    if arac_ismi == "10":
        return data_10
    if arac_ismi == "25":
        return data_25
    if arac_ismi == "34":
        return data_34
    if arac_ismi == "37":
        return data_37


def son_30_dk(time, isim):
    suanki_saat = time
    yarım_saat_oncesi = time-30 
    x_list=[]
    y_list=[]
    date_list=[]
    time_point=[]
    isim1=isim[0]
    if isim1 == "10":
        for veri in data_10:
            if veri["time_p"]>yarım_saat_oncesi and veri["time_p"]<suanki_saat:
                x_list.append(veri["x"])
                y_list.append(veri["y"])
                date_list.append(veri["date"])
    if isim1 == "25":
        for veri in data_25:
            if veri["time_p"]>yarım_saat_oncesi and veri["time_p"]<suanki_saat:
                x_list.append(veri["x"])
                y_list.append(veri["y"])
                date_list.append(veri["date"])
    if isim1 == "34":
        for veri in data_34:
            if veri["time_p"]>yarım_saat_oncesi and veri["time_p"]<suanki_saat:
                x_list.append(veri["x"])
                y_list.append(veri["y"])
                date_list.append(veri["date"])
    if isim1 == "37":
        for veri in data_37:
            if veri["time_p"]>yarım_saat_oncesi and veri["time_p"]<suanki_saat:
                x_list.append(veri["x"])
                y_list.append(veri["y"])
                date_list.append(veri["date"])

    
    
    data_new = []
    for i in range(len(x_list)):
        
        veri = {
        "x": 0,
        "y": 0,
        "date": 0
        }
        veri.update({"x": x_list[i]})
        veri.update({"y": y_list[i]})
        veri.update({"date": date_list[i]})
        data_new.append(veri)


    data_new = pd.DataFrame(data_new)
    data_new = data_new.sort_values("date",ignore_index=True)

    x_db = data_new["x"]
    y_db = data_new["y"]
    dt_db = data_new["date"]

    data_new2 = []
    for i in range(len(x_db)):
        veri = {
        "x": 0,
        "y": 0,
        "date": 0
        }
        veri.update({"x": x_db[i]})
        veri.update({"y": y_db[i]})
        veri.update({"date": dt_db[i]})
        data_new2.append(veri)   

    return data_new2    

def get_data_time(saat1,saat2,dakika1,dakika2,arac):


        data_aractime=[]
        
        if arac == "10":
            data_aractime=data_10
        if arac == "25":
            data_aractime=data_25
        if arac == "34":
            data_aractime=data_34
        if arac == "37":
            data_aractime=data_37
        

        
        
        x_listaractime=[]
        y_listaractime=[]
        date_listaractime=[]
        dgr_1 = (int(saat1)*60)+int(dakika1)
        dgr_2 = (int(saat2)*60)+int(dakika2)

        if dgr_2<=dgr_1 :
            return 0
        
        for veri in data_aractime:
            if veri["time_p"]>(dgr_1) and veri["time_p"]<(dgr_2):
                x_listaractime.append(veri["x"])
                y_listaractime.append(veri["y"])
                date_listaractime.append(veri["date"])
        

        
        
        data_yeni2 = []
        for i in range(len(x_listaractime)):
            veri = {
            "x": 0,
            "y": 0,
            "date": 0
            }
            veri.update({"x": x_listaractime[i]})
            veri.update({"y": y_listaractime[i]})
            veri.update({"date": date_listaractime[i]})
            data_yeni2.append(veri)

        data_yeni2 = pd.DataFrame(data_yeni2)
        data_yeni2 = data_yeni2.sort_values("date",ignore_index=True)

        x_db_2 = data_yeni2["x"]
        y_db_2 = data_yeni2["y"]
        dt_db_2 = data_yeni2["date"]
        data_new4 = []
        boyut = int(len(x_db_2))
        boyut = boyut-1
        for i in range(boyut):
            veri_ = {
                "x": 0,
                "y": 0,
                "date": 0
            }
            veri_.update({"x":x_db_2[i]})
            veri_.update({"y":y_db_2[i]})
            veri_.update({"date":dt_db_2[i]})
            data_new4.append(veri_)

        
        return data_new4

bp=Blueprint("home",__name__,template_folder="../templates",static_folder="../static")

@bp.route("/")
def Index():
    username, login_auth = GetCurrentUsername()
    
    return render_template("login.html", username=username, login_auth=login_auth)

@bp.route("/login")
def Login():
    username, login_auth = GetCurrentUsername()
    
    return render_template("login.html", username=username, login_auth=login_auth)
@bp.route("/map1")
def map1():
    username, login_auth = GetCurrentUsername()
    now = datetime.now()

    print("now =", now)

    # dd/mm/YY H:M:S
    dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
    dt_string=dt_string.split(" ")[1]
    x1=dt_string.split(":")[0]
    x2=dt_string.split(":")[1]
    print("Saat:"+x1+"Dakika:"+x2)	
    
    Giris=GirisTarih(username)
    # x = str(datetime.datetime.now())
    # x=x.split(" ")[1]
    # x1=x.split(":")[0]
    # x2=x.split(":")[2].split(".")[0]
    # x=x1+":"+x2
    # x=x.split(":")
    
    suankisaat=(int(x1)*60 +int(x2))
    vehichles=Arac_sorgu(username)
    
    build()
    arac1 = vehichles[0]
    arac2 = vehichles[1]
    data_1= son_30_dk(suankisaat,arac1)
    
    data_2= son_30_dk(suankisaat,arac2)
    
    return render_template('map1.html',  data1 = data_1 ,data2 = data_2,Giris=Giris)
    

@bp.route("/secim")
def secim():
    
    username,login_auth = GetCurrentUsername()
    Giris=GirisTarih(username)
    vehichles=Arac_sorgu(username)
    varmi = {
            "10": 0,
            "25": 0,
            "34": 0,
            "37": 0
            }
    
    for vehichle in vehichles:
        if(vehichle[0]=='10'):

Yazlab_2.1/app/views/users.py
from flask import request, redirect, url_for, render_template, abort,Blueprint
from app.controllers import UserLogin, GetCurrentUsername, UserLogout 

import sqlite3
import os
from app.models.models import  cikis


currentdirectory=os.path.dirname(os.path.abspath(__file__))

bp=Blueprint("users",__name__,template_folder="../templates")

@bp.route("/",methods=["GET","POST"])
def Login():
    if request.method == "POST":
        if request.form:
            if "username" in request.form and "password" in request.form:
                username = request.form["username"]
                password = request.form["password"]
                if UserLogin(username, password):
                #if User_sorgu(username, password):
                    return redirect(url_for("home.map1"))#secim ekranı
                else:
                    return redirect(url_for("home.Login"))
                #SELECT name from Database
        abort(400)
    username, login_auth = GetCurrentUsername()
    return render_template("login.html", username=username, login_auth=login_auth)

@bp.route("/logout")
def Logout():
    username, login_auth = GetCurrentUsername()
    if UserLogout():
        cikis(username)
        return redirect(url_for("home.Index"))

Yazlab_2.1/app/templates/base.html
<!DOCTYPE HTML>
<!--
	Intensify by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>yazlab 2.1</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="static/assets/css/main.css" />
	</head>
    <body>

		<!-- Header -->
			<header id="header">
				
				<a class="logo">Araç Takip Sistemi</a>
				
                
                
                
				
				
			</header>
       
            {% block body_content %}
            {% endblock %}


        <!-- Scripts -->
            <script src="static/assets/js/jquery.min.js"></script>
            <script src="static/assets/js/jquery.scrolly.min.js"></script>
            <script src="static/assets/js/skel.min.js"></script>
            <script src="static/assets/js/util.js"></script>
            <script src="static/assets/js/main.js"></script>







    </body>
</html>

Yazlab_2.1/app/templates/login.html
<!DOCTYPE HTML>
{% extends 'base.html' %}
{% block body_content %}

<section id="one" class="wrapper">
    <div class="inner">
        <form method="post" action="{{ url_for('users.Login') }}">
            <div class="row uniform">
                <div class="6u 12u$(xsmall)">
                    <input type="text" name="username" id="name" value="" placeholder="Kullanici Adi" />
                </div>
                <div class="6u$ 12u$(xsmall)">
                    <input type="password" name="password" id="password" value="" placeholder="Şifre" />
                </div>
                <div class="12u$">
                    <ul class="actions">
                        <li><input type="submit" value="Giriş yap" href="{{ url_for('home.map1') }}" /></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
</section>

{% endblock %}

Yazlab_2.1/app/templates/map1.html
<html>
<head>
	<style>
        .myDiv {
          border: 3px outset rgba(255, 0, 0, 0);
          background-color: lightblue;
          text-align: center;
        }
        </style>

        <div class="myDiv">
            <h2> Kullanıcı Giriş Zamanı:{{Giris[0][0]}}  </h2>
            
        </div>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
	<link rel="stylesheet" href="static/assets/css/main.css" />
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
        crossorigin="anonymous">
        
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<YOURAPIKEY>&callback=initMap"></script>
<script type="text/javascript">
    function initialize() {
        const myLatLng = { lat: 59.85855203, lng: 17.64521252 };
        var map = new google.maps.Map(document.getElementById("map_canvas"), {
            zoom: 8,
            center: myLatLng,
        });

        var marker_icon_FF0000 = {
            url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAiCAYAAACwaJKDAAAABmJLR0QA/wD/AP+gvaeTAAACBklEQVRIia3VzUtUURgH4GdG/AiyZZShtWgXUbSIFtGqRYtqWRLhXyBYf0K6MaJQ2gRtayHtijYpleHKSCgIcRHoIiOSKEzLKea0OOeqTfPlzPzg5Qwz9zz3nXPvPTeneo7gNA4gjyI+Ygbva8z9L2cxi9BHOE+4msY+gliz6biayWE0R7GfMEcoEkJJzRH6CbnY+WiaVxEc6yY8KQOVq8eE7tj1WCV4qIswUyeY1QyhK8JDpWAP1m7vEMzqTkTXkrOZkYOEQoNogXAowiPE2wQuDqC9nktZJu0YSE72XRs2phrsMqup2OkG2vLpRB19DXaZJc3vQHv294Um0e3z8yigsNQkmuYXUMie5/npJtE0fz55YLiXsNHELdUbV2B4+4n2Y/Vmg+itCK4m558MdhBe7hCcJnRGdLDS0ox3E17XCb4h7IngeLX1zuFhD2G5BriytY4Tqmx9WXbh3Tnl99KsLkdwAbtrgVmO4/eDCuCkzd3/TL1glru9hF8lYJFwMoKPdgrCXqzfL0GfR7CIo42gcO9YCXopolONgnAC4W0Cv9l8dVxpBoWFGwmdiOC6Glc8X+3HlKeT6cOzOLzAjyaaBBc602ZzOHZ6vVkQ9kl7Qi6ip1qBwpdrEfwjPnFVU8+awuKrOC7hZ6vQlQ9baM3Ui379HsfVVqKf07jcSvRTGhfrOfgvIP3ECS77BDoAAAAASUVORK5CYII=",
            labelOrigin: new google.maps.Point(10, 11)
        };

       

        {% for veri in data1 %}

            new google.maps.Marker({
                position: new google.maps.LatLng({{veri["x"]}},{{veri["y"]}}),
                icon: marker_icon_FF0000,
                map: map
            });
            
        {% endfor %}
        
        const array = []

        {% for veri in data1 %}

        new google.maps.Marker({

        position: { lat: {{ veri["x"] }}, lng: {{ veri["y"] }} },
        map,
        icon:"http://maps.google.com/mapfiles/ms/icons/blue-dot.png",
        title: "Hello World!",
        });

        {% endfor %} 

        new google.maps.Polyline({
            clickable: false,
            geodesic: true,
            strokeColor: "red",
            strokeOpacity: 1.000000,
            strokeWeight: 2,
            map: map,
            path: [
            {% for veri in data1 %}

                new google.maps.LatLng({{veri["x"]}}, {{veri["y"]}}),
        
    
            {% endfor %}
                
            ]
        });

        {% for veri in data2 %}

            new google.maps.Marker({
                
                position: { lat: {{ veri["x"] }}, lng: {{ veri["y"] }} },
                map,
                icon:"http://maps.google.com/mapfiles/ms/icons/yellow-dot.png",
                title: "Hello World!",
            });

        {% endfor %}

        new google.maps.Polyline({
            clickable: false,
            geodesic: true,
            strokeColor: "#0000FF",
            strokeOpacity: 1.000000,
            strokeWeight: 2,
            map: map,
            path: [
            {% for veri in data2 %}

                new google.maps.LatLng({{veri["x"]}}, {{veri["y"]}}),
        
    
            {% endfor %}
                
            ]
        });

    }
    function geri(){
    
        history.go(-1)

    }
</script>
</head>
<body style="margin:0px; padding:0px;" onload="initialize()">
    <div id="map_canvas" style="width: %80; height: 500px;" ></div>

    <section id="banner">
			<div class="content">
				
				<ul class="actions">
					<li><a href="{{ url_for('home.secim' ) }}" class="button scrolly">Seçim</a></li>
				</ul>
			</div>
            <div class="content">
				
				<ul class="actions">
                    <a href="{{ url_for('users.Logout') }}" class="button scrolly">{{ username }} Çıkış</a>
                </ul>
			</div>
		</section>
        
        <div class="myDiv">
            <br> Veriler:</br>
            <br> Data1:</br>
            {% for veri1 in data1 %}
                {{veri1["date"]}} # {{veri1["x"]}} # {{veri1["y"]}}</br>
            {% endfor %}
            <br> Data2:</br>
            {% for veri2 in data2 %}
                {{veri2["date"]}} # {{veri2["x"]}} # {{veri2["y"]}}</br>
            {% endfor %}
        </div>
</body>
</html>

Yazlab_2.1/app/templates/map2.html
<html>
    <head>
        <style>
            .myDiv {
              border: 3px outset rgba(255, 0, 0, 0);
              background-color: lightblue;
              text-align: center;
            }
            </style>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8" />
        <link rel="stylesheet" href="static/assets/css/main.css" />
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
            integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
            crossorigin="anonymous">
            
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<YOURAPIKEY>&callback=initMap"></script>
<script type="text/javascript">
    function geri(){
    
        history.go(-1)

    }
    function initialize() {
        const myLatLng = { lat: 59.85855203, lng: 17.64521252 };
        var map = new google.maps.Map(document.getElementById("map_canvas"), {
            zoom: 10,
            center: myLatLng
        });

        var marker_icon_FF0000 = {
            url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAiCAYAAACwaJKDAAAABmJLR0QA/wD/AP+gvaeTAAACBklEQVRIia3VzUtUURgH4GdG/AiyZZShtWgXUbSIFtGqRYtqWRLhXyBYf0K6MaJQ2gRtayHtijYpleHKSCgIcRHoIiOSKEzLKea0OOeqTfPlzPzg5Qwz9zz3nXPvPTeneo7gNA4gjyI+Ygbva8z9L2cxi9BHOE+4msY+gliz6biayWE0R7GfMEcoEkJJzRH6CbnY+WiaVxEc6yY8KQOVq8eE7tj1WCV4qIswUyeY1QyhK8JDpWAP1m7vEMzqTkTXkrOZkYOEQoNogXAowiPE2wQuDqC9nktZJu0YSE72XRs2phrsMqup2OkG2vLpRB19DXaZJc3vQHv294Um0e3z8yigsNQkmuYXUMie5/npJtE0fz55YLiXsNHELdUbV2B4+4n2Y/Vmg+itCK4m558MdhBe7hCcJnRGdLDS0ox3E17XCb4h7IngeLX1zuFhD2G5BriytY4Tqmx9WXbh3Tnl99KsLkdwAbtrgVmO4/eDCuCkzd3/TL1glru9hF8lYJFwMoKPdgrCXqzfL0GfR7CIo42gcO9YCXopolONgnAC4W0Cv9l8dVxpBoWFGwmdiOC6Glc8X+3HlKeT6cOzOLzAjyaaBBc602ZzOHZ6vVkQ9kl7Qi6ip1qBwpdrEfwjPnFVU8+awuKrOC7hZ6vQlQ9baM3Ui379HsfVVqKf07jcSvRTGhfrOfgvIP3ECS77BDoAAAAASUVORK5CYII=",
            labelOrigin: new google.maps.Point(10, 11)
        };

       

        {% for veri in data %}

            new google.maps.Marker({
                position: new google.maps.LatLng({{veri["x"]}},{{veri["y"]}}),
                icon: marker_icon_FF0000,
                map: map
            });
            
        {% endfor %}
        
       

        

        new google.maps.Polyline({
            clickable: false,
            geodesic: true,
            strokeColor: "#0000FF",
            strokeOpacity: 1.000000,
            strokeWeight: 2,
            map: map,
            path: [
            {% for veri1 in data %}

                new google.maps.LatLng({{veri1["x"]}}, {{veri1["y"]}}),
        
    
            {% endfor %}
                
            ]
        });

    }
</script>
</head>
<body style="margin:0px; padding:0px;" onload="initialize()">
    <div id="map_canvas" style="width: %100; height: 500px;"></div>

        
    <section id="banner">
        <div class="content">
            
            <ul class="actions">
                <a href="{{ url_for('home.secim') }}" class="button scrolly"> Geri Dön</a>
            </ul>
        </div>
        
    
    
        <div class="content"><div>
            <ul class="actions">
                <a href="{{ url_for('users.Logout') }}" class="button scrolly">{{ username }} Çıkış</a>
            </ul>
        </div>    
    </section>  

    <div class="myDiv">
        <br> Veriler:</br>
        <br> Data:</br>
        {% for veri1 in data %}
            {{veri1["date"]}} # {{veri1["x"]}} # {{veri1["y"]}}</br>
        {% endfor %}
        
    </div>
    
</body>
</html>